#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2018-01-09  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 list-size\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

count=$1

./bench.sh $count 2>&1 | tee Results/`hostname -s`-`uname -p`-$count
