#!/bin/sh -e

# Nothing about pointer optimizations in release notes:
# https://releases.llvm.org/9.0.0/docs/ReleaseNotes.html

cc -o genrand genrand.c
./genrand 100000 > 100000nums
for CC in clang80 clang90 clang13; do
    $CC --version
    for opt in -O -O2 -Ofast; do
	echo $opt
	$CC $opt -o selsort-subscripts selsort-subscripts.c
	$CC $opt -o selsort-pointers selsort-pointers.c
	    printf "Subscripts: "
	    time ./selsort-subscripts < 100000nums > /dev/null
	    printf "Pointers:   "
	    time ./selsort-pointers < 100000nums > /dev/null
    done
done
