#!/compat/linux/bin/bash

set -e

# Remarkably, Matlab does not tolerate a '-' in a filename
# Using selsort-vectorized.m, matlab tries to run selsort.m
printf "Matlab vectorized...\n"
time /compat/linux/usr/MATLAB/R2018a/bin/matlab \
    -nojvm -r "run('selsort-vectorized.m');" > sorted-matlabv

printf "Matlab explicit loop...\n"
time /compat/linux/usr/MATLAB/R2018a/bin/matlab \
    -nojvm -r "run('selsort.m');" > sorted-matlab
